### ISSUE TITLE
unable to run make.R script

### ISSUE THREAD

**Issue by DeniseJGreig** [ecohealthalliance/eidith-cleaning-reports#12]
I did get-eidith-data and had the following warning (25 times):
Unknown or uninitialised column: 'Country'.

Then, when I tried to run the make.R script (for Cambodia), I got this error:
Quitting from lines 224-235 (report-template.Rmd)
Error in UseMethod("pull") :
 no applicable method for 'pull' applied to an object of class "NULL"

On the upside - I talked Lucy Keatts through it and hers worked perfectly!!!

**Comment by noamross** [comment]
Thanks for the report, @DeniseJGreig.  Have you updated the **eidith** package recently? We made some changes to it to keep up with upstream changes in EIDITH.  Please run `remotes::install_github("ecohealthallince/eidith")` and let us know if this fixes things.

Note we also just made a small change to this repository to allow you to select which countries data you want to _download_, which can be convenient when you just want to run one country and not wait forever for all the data.

**Comment by DeniseJGreig** [comment]
Ah. OK. When I do that, I get the following errors:
Error: (converted from warning) cannot remove prior installation of package ‘DT’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I installed the package DT and ran get-eidith-data.R and got these errors:
 Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘R6’ 2.2.2 is being loaded, but >= 2.4.0 is required 
I installed namespace, but got the same message. deleted namespace, restarted R, reinstalled it, same error.

**Comment by noamross** [comment]
It seems like a few things may need to update.  Can you try (in a fresh session), `devtools::install_deps(upgrade = "always")`?

**Comment by DeniseJGreig** [comment]
OK. one warning from that....
package ‘fs’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘fs’

**Comment by noamross** [comment]
And you have nothing loaded in the fresh session when you run `install_deps()`? That error is usually related to having that package loaded while trying to install over it.

In any case, try `install.packages('fs')`, then `devtools::install_deps(upgrade = "always")` again?

Installation is so much more of pain than usage.

**Comment by DeniseJGreig** [comment]
I know....this time I got:
Error: (converted from warning) cannot remove prior installation of package ‘processx’

**Comment by DeniseJGreig** [comment]
I don't know if I have anything loaded on not. Just did "quit session" and then reopened RStudio. Maybe I am not clearing the session correctly?

**Comment by DeniseJGreig** [comment]
I felt like I made some progress, but it is still having an issue with namespace no matter how many times I install it. I don't understand which versions it is referring to either as the RStudio packages tab says that I have namespace package version 0.9.1 and my R is 3.5 or something

Quitting from lines 12-27 (report-template.Rmd) 
Error: package or namespace load failed for 'tidyverse' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'R6' 2.2.2 is already loaded, but >= 2.4.0 is required

**Comment by eveskew** [comment]
Hi Denise. Sorry you're still having trouble. Not sure if it's going to help, but that error message is not actually about the package called `namespace`. Rather, it's telling you that you need the `R6` package, version 2.4.0 or higher, while you only have version 2.2.2 on your machine (and it's also loaded into your R session at the time of attempted installation).

Are you running on a Mac or Windows machine? I wonder if perhaps some packages are being initialized at the start of your R session (without you realizing it) that prevent successful installation.

**Comment by DeniseJGreig** [comment]
it actually seems to be slowly acquiring the raw data now...we'll see how it goes.
this time, I started a new session, installed namespace, then ran the devtools::install_deps()
I am on a PC and I think you are right - I must have something old sitting in the background somewhere. Thanks for sticking with me.

**Comment by noamross** [comment]
Hi @DeniseJGreig! Just following up here to check whether things have worked out.

**Comment by DeniseJGreig** [comment]
Yes, I finally got Cambodia to work yesterday. I'm not sure which install
or update finally did the trick. And then it took forever for the raw data
to come through on my crappy home wifi, but it worked. So cool!!!!! Thanks
for asking, Denise

**Comment by noamross** [comment]
Great! Good to know.  We also just pushed a change that allows you to pull data for individual countries selectively (see the README), so that might help with slow downloads in the future.

**Comment by DeniseJGreig** [comment]
Awesome! That will definitely be useful!
